### ISSUE TITLE
Determine parameters for OTDD

### ISSUE THREAD

**Issue by joannacknight** [alan-turing-institute/arc-model-similarities-phase-2#48]
Following the implementation of OTDD in issue #7, it will be necessary to identify appropriate parameters for the calculation in the experiments. 

Will the exact calculation be feasible between the real datasets when using the HPC? Or will an approximation be required?

**Comment by joannacknight** [comment]
I think it is worth running the OTDD in the first instance with the 'exact' settings on the whole dataset and seeing the computational effort involved. I would expect this to run on the HPC as it can make use of the GPU.

**Comment by philswatton** [comment]
This was done with #59
